name: Build

on:
  push:
    branches:
      - develop
    paths:
      - "src/**/*.rs"
      - rust-toolchain.toml
      - Cargo.toml
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Build/test on ${{ matrix.name }}

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            use-cross: true
          - name: macOS (Intel)
            os: macos-latest
            target: x86_64-apple-darwin
            use-cross: false
          - name: macOS (Apple Silicon)
            os: macos-latest
            target: aarch64-apple-darwin
            use-cross: false

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true
          show-progress: true
          submodules: recursive

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build (release)
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.use-cross }}
          command: build
          args: --verbose --release --target ${{ matrix.target }}

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.use-cross }}
          command: test
          args: --verbose --release --target ${{ matrix.target }}

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true
          show-progress: true
          submodules: recursive

      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Cargo release
        id: cargo_release
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          cargo install --quiet cargo-smart-release
          git config --global user.email "ci@pilgrimagesoftware.com"
          git config --global user.name "Pilgrimage Software CI"
          cargo smart-release \
            --bump auto \
            --update-crates-index \
            --allow-fully-generated-changelogs \
            --signoff \
            --no-publish \
            --commit-prefix "chore: release [skip ci]" \
            --execute
