name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  pages: write
  id-token: write

concurrency: release

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # full history required for git-cliff
          fetch-tags: true
          show-progress: true
          submodules: recursive

      - name: Install Rust
        id: install_rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust cache
        id: rust_cache
        uses: Swatinem/rust-cache@v2

      - name: Install git-cliff
        id: install_git_cliff
        uses: taiki-e/install-action@git-cliff

      - name: Test
        id: test
        run: |
          cargo test --all-features

      - name: Publish to crates.io
        id: publish_crate
        run: |
          cargo publish

      - name: Generate changelog for this tag
        id: changelog
        run: |
          git-cliff --current --strip header -o RELEASE_NOTES.md

      - name: Create GitHub Release
        id: github_release
        uses: softprops/action-gh-release@v3
        with:
          body_path: RELEASE_NOTES.md
